### ISSUE TITLE
Error with mailgun

### ISSUE THREAD

**Issue by aarcascuerda** [AgileDS/AutoScorer#7]
There's some setting of mailgun not well configured. (Probably just one enviroment setting or something like that).

The error that the server gives after trying to log Mailgun:

: ERROR 2019-11-04 20:29:58,877 log 11 139933496672384 Internal Server Error: /accounts/login/
2019-11-04T19:29:59.169097+00:00 app[web.1]: Traceback (most recent call last):
2019-11-04T19:29:59.1691+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/allauth/account/utils.py", line 302, in send_email_confirmation
2019-11-04T19:29:59.169102+00:00 app[web.1]: email_address = EmailAddress.objects.get_for_user(user, email)
2019-11-04T19:29:59.169105+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/allauth/account/managers.py", line 49, in get_for_user
2019-11-04T19:29:59.169107+00:00 app[web.1]: email__iexact=email)
2019-11-04T19:29:59.169109+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
2019-11-04T19:29:59.169111+00:00 app[web.1]: return getattr(self.get_queryset(), name)(*args, **kwargs)
2019-11-04T19:29:59.169113+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
2019-11-04T19:29:59.169115+00:00 app[web.1]: self.model._meta.object_name
2019-11-04T19:29:59.169118+00:00 app[web.1]: allauth.account.models.EmailAddress.DoesNotExist: EmailAddress matching query does not exist.

**Comment by aarcascuerda** [comment]
Added an account and the login settings in the environment and it works.
Closing
